# Title of your blog; shows in the header
name: "Memoirs of a Cherry-dev"

# Description of your content (will only be used on Google Search)
description: "Snippets and shiny things from my experience as a software engineer"

# Your name. Will show in your footer + sidebar
author: "Kadyn Martinez"

url: "http://KadynCBR.github.io"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Currently I work as a Robotics software engineer. This blog is meant to be a place for me to keep record of my experiences and hopefully help some other wandering souls along. I dabble in robotics, computer vision, machine learning, and game development."

# Social Accounts (mine, as placeholders)

github: KadynCBR

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
